name: Manage Node Commons

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/manage-repo-common-node.yaml"
      - "common/node/**"
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          You can specify the repository's name where files should be pushed manually, as long as workflow settings do not ignore the repository.
          If you do not specify the exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false

jobs:
  replicate_directus_common:
    name: Wellenplan Node commons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replicating files
        # TODO: get rid of fork once this is merged:
        # - https://github.com/derberg/copy-files-to-other-repositories/pull/37
        # The patch also contains a fix for a missing build in v1.0.1.
        #uses: derberg/copy-files-to-other-repositories@v1.0.1
        uses: hairmare/copy-files-to-other-repositories@hairmare
        with:
          github_token: ${{ secrets.ORGA_USER_TOKEN }}
          patterns_to_include: "common/node/"
          dispatch_root: "common/node"
          topics_to_include: "nodejs"
          destination: "./"
          committer_username: wellenplan-bot
          committer_email: noreply@github.com
          commit_message: "chore: update Wellenplan Node commons"
